name: EcoWear CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        working-directory: ./ecowear-frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./ecowear-frontend
        run: npm run build

      - name: Install Backend Dependencies
        working-directory: ./ecowear-backend
        run: npm install

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Frontend Docker Image
        run: docker build -t sasmalrohit2004/ecowear-frontend:latest ./ecowear-frontend

      - name: Build Backend Docker Image
        run: docker build -t sasmalrohit2004/ecowear-backend:latest ./ecowear-backend

      - name: Push Frontend Image
        run: docker push sasmalrohit2004/ecowear-frontend:latest

      - name: Push Backend Image
        run: docker push sasmalrohit2004/ecowear-backend:latest

      # AWS authentication
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::853679583085:role/GitHubActions-EcoWear-CD
          aws-region: eu-north-1

      # SAFE CD TEST - does not modify anything
      - name: Test SSM Connection
        run: |
          aws ssm send-command \
            --instance-ids i-0a7616b70e8f682d5 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["docker ps"]' \
            --region eu-north-1